### ISSUE TITLE
Agent selector does not use ACRONYM 

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#590] opened 2024-04-23 02:22 UTC
<img width="462" alt="Capture d’écran 2024-04-22 à 23 22 04" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/b866c729-f29c-426d-98f5-5d2c60e9a3a0">

**Comment by jonquet** [comment] 2024-04-23 02:26
Plus, the agent selector display "ACRONYM" rather than the actual acronym of the organization... it might be linked. 
Need to be corrected and a space added. 
<img width="369" alt="Capture d’écran 2024-04-22 à 23 24 48" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/d2084f6d-52e7-46c2-ae9f-a621418185ee">

**Comment by syphax-bouazzouni** [comment] 2024-06-10 07:20
duplicate of https://github.com/agroportal/project-management/issues/571

**Closed by syphax-bouazzouni** 2024-06-10 07:20 UTC
Labels: enhancement
