### ISSUE TITLE
Select name in the metadata administration form generate a "Content missing" error

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#763] opened 2024-10-01 06:54 UTC
<img width="238" alt="Capture d’écran 2024-09-30 à 23 54 17" src="https://github.com/user-attachments/assets/ebe74ca9-3810-41c9-921b-e5b8fa2a34d4">

**Comment by syphax-bouazzouni** [comment] 2024-10-01 06:59
duplicate of https://github.com/agroportal/project-management/issues/591

**Closed by syphax-bouazzouni** 2024-10-01 06:59 UTC
Labels: bug
